#!/bin/sh
#PBS -N BigDFT-tests-OMP
#PBS -j oe
#PBS -A UT-TENN0041

### Unused PBS options ###
## If left commented, must be specified when the job is submitted:
## 'qsub -l walltime=hh:mm:ss,nodes=12:ppn=4'
##
#PBS -l walltime=04:00:00
#PBS -l nodes=1:ppn=6

### End of PBS options ###

date
cd $PBS_O_WORKDIR

echo "nodefile="
cat $PBS_NODEFILE
echo "=end nodefile"

# run the program
export OMP_NUM_THREADS=2

mpirun -cpus-per-proc 2 /lustre/medusa/genovese/1.6-dev.21/src/bigdft B80 > out

date

# eof
